version: 2

jobs:
  build:
    docker:
      - image: esplinux/bootstrap
    environment:
      VERSION: "0.01"
    steps:
      - checkout
      - run:
          name: Build
          shell: /bin/sh -e
          command: |
            esp add ghr espbuild
            echo gnu >> /etc/esp-repos
            espbuild ${CIRCLE_PROJECT_REPONAME}.conf
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/package
